name: titletk
favicon: null
layout_spectrum: 0.38363
typography_spectrum: 0.22069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcd2b7'
    - '#c4b9a0'
    - '#aea38c'
    - '#726959'
    - '#3f382f'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
