name: titletk
favicon: null
layout_spectrum: 0.50333
typography_spectrum: 0.22069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e2128'
    - '#43464d'
    - '#0a0d12'
    - '#6e6c77'
    - '#a1a898'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
